[project]
name = "lol-api"
version = "0.1.0"
description = "League of Legends API client and frontend"
readme = "README.md"
requires-python = ">=3.9.7"
license = {text = "MIT"}
authors = [{name = "Nolan Meyer", email = "meyer09@gmail.com"}]
dependencies = [
    "matplotlib>=3.8.1",
    "pandas>=2.1.3",
    "psycopg2>=2.9.9",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
    "streamlit>=1.28.2",
    "sqlalchemy",
]

[project.optional-dependencies]
test = ["pytest", "selenium"]

[project.urls]
repository = "https://github.com/Nolasaurus/League_of_Legends_SQL_db"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
pythonpath = ["src"]

[tool.coverage.run]
source = ["src/"]